name: orbit-dataset
channels:
  - pytorch
  - plotly
  - nvidia
dependencies:
  - python=3.7
  - pip=22.2.2
  - plotly=4.8.1
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - torchvision=0.14.1
  - tqdm=4.62.3
  - ipykernel=6.15.2
  - jupyter=1.0.0
  - pip:
    - thop==0.1.1.post2209072238
    - timm==0.6.12
